### PR TITLE
adding search keyword translation

### PR DESCRIPTION
**Pull request by yomiodeleye**
### What

adding localised translation for search keyword in both english and welsh

### How to review
By changing the localised  from english to welsh and see if the text for "Search Keyword" changes to welsh 

### Who can review

Frontend Developers

### CODE REVIEW

**Comment by gilesburdett** [comment]
I've had an idea for another approach with the localisation that could simplify this and other work we've yet to do. Nick and I are in the middle of discussing it and we'll follow up on this this afternoon and let you know.

**Review by gilesburdett — CHANGES_REQUESTED** [review]

**Comment by gilesburdett** [comment]
@yomiodeleye Please run `go fmt` on the mapper and then it'll be ready for approval.

**Comment by yomiodeleye** [comment]
just run  go fmt and notting changes. So i think is ok

**Comment by gilesburdett** [comment]
Running `go fmt mapper/mapper.go` will result in this formatting delta:

```
        calendar.KeywordSearch = coreModel.CompactSearch{
-               ElementId:  "keyword-search",
-               InputName:  "keywords",
-               Language:   calendar.Language,
+               ElementId:        "keyword-search",
+               InputName:        "keywords",
+               Language:         calendar.Language,
                LabelLocaliseKey: "ReleaseCalendarPageSearchKeywords",
-               SearchTerm: "zip zap zoo",
+               SearchTerm:       "zip zap zoo",
        }
```

Please fix and commit to progress this PR.

**Comment by yomiodeleye** [comment]
Indentation issues is now resolved

**Review by gilesburdett — APPROVED** [review]

**Pull request merged**
